repos:
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    language_version: python3
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi]
  - id: black-jupyter
    name: black-jupyter
    description:
      "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
    entry: black
    language: python
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi, jupyter]
    additional_dependencies: [".[jupyter]"]

- repo: https://github.com/pycqa/flake8
  rev: 7.2.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-simplify

- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.15.0
  hooks:
  - id: reorder-python-imports
    args: [--py310-plus, --add-import, "from __future__ import annotations"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-builtin-literals
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: name-tests-test
    - id: file-contents-sorter
      files: |
        (?x)^(
          .*requirements(-\w+)?.(in|txt)|
          requirements/.*\.txt|
          .gitignore
        )

# - repo: https://github.com/PyCQA/pydocstyle
#   rev: 6.3.0
#   hooks:
#   - id: pydocstyle
#     files: bmipy/.*\.py$
#     args:
#     - --convention=numpy
#     - --add-select=D417
#     additional_dependencies: [".[toml]"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.0
  hooks:
  - id: mypy
    language_version: python3.12
    files: src/.*\.py$

- repo: https://github.com/mcflugen/heartfelt-hooks
  rev: v0.3.3
  hooks:
  - id: check-whitespace
  - id: check-heading-levels

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
    - id: nbqa-pyupgrade
      args: ["--py310-plus"]
    - id: nbqa-isort
    - id: nbqa-flake8
      args: ["--extend-ignore=E402"]

- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
      description: Strip output from jupyter notebooks
      args: [--drop-empty-cells]
