name: Test

on:
  pull_request:
  push:
    branches: ["**"]
  workflow_dispatch:
    inputs:
      publish_to:
        description: "Where to publish"
        type: choice
        required: true
        default: none
        options:
          - none
          - testpypi
          - pypi

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: build-sdist
          path: ${{ github.workspace }}/dist/*.tar.gz

  test:
    needs: build-sdist
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13", "3.14"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v4
        name: Download build artifacts
        with:
          pattern: "build-*"
          merge-multiple: true
          path: ${{ github.workspace }}/dist

      - name: Test
        run: |
          pip install nox
          nox --non-interactive -s test -- dist/*.tar.gz

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    needs: build-sdist
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - name: Use Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/download-artifact@v4
        name: Download build artifacts
        with:
          pattern: "build-*"
          merge-multiple: true
          path: ${{ github.workspace }}/dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build documentation
        run: |
          pip install nox
          nox -s docs-build -- dist/*.tar.gz

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/html/

  deploy-docs:
    needs: docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish:
    needs:
      - test
      - build-sdist
    name: "Publish to PyPI/TestPyPI"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.publish_to != 'none'
    env:
      REPOSITORY_URL: ${{ inputs.publish_to == 'testpypi' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: "build-*"
          merge-multiple: true
          path: ${{ github.workspace }}/dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ env.REPOSITORY_URL }}
          packages-dir: dist
          skip-existing: true
          print-hash: true
          verify-metadata: false
